Numpy Assignment.

In [64]:
import numpy as np

In [40]:
#assingment1
#q-1
a= np.random.randint(1, 21, size=(5, 5))
print(f"Old:\n {a}")

a[:,2]=1
print(f"New:\n{a}")


Old:
 [[19  2 19 12 20]
 [ 7 10 14  6  8]
 [ 2 10 19 16 12]
 [19  2  2  5  6]
 [15  1  9  9  4]]
New:
[[19  2  1 12 20]
 [ 7 10  1  6  8]
 [ 2 10  1 16 12]
 [19  2  1  5  6]
 [15  1  1  9  4]]


In [43]:
#q-2
x=np.random.randint(1,17, size=(4,4))
print(f"Old:\n {x}")
np.fill_diagonal(x, 0)
print(f"New:\n{x}")


Old:
 [[ 5  7  7 15]
 [ 7  9  5 11]
 [ 8 12 11  1]
 [11  4  7  8]]
New:
[[ 0  7  7 15]
 [ 7  0  5 11]
 [ 8 12  0  1]
 [11  4  7  0]]


In [50]:
#assignment2
#q-1
y=np.random.randint(1,37 , size=(6,6))
print(f"The array:{y}")
z=y[2:5,:]
print(f"3rd to 5th row:\n{z}")
w=y[1:4,:]
print(f"2nd to 4th row:\n{w}")

The array:[[10 24  8 10 14 14]
 [16  1 14 23 34 18]
 [ 7  5 36 32  1 15]
 [32 23 13 27 28 13]
 [11 24 27 18 23 25]
 [21  9 11 25 17 22]]
3rd to 5th row:
[[ 7  5 36 32  1 15]
 [32 23 13 27 28 13]
 [11 24 27 18 23 25]]
2nd to 4th row:
[[16  1 14 23 34 18]
 [ 7  5 36 32  1 15]
 [32 23 13 27 28 13]]


In [61]:
#q-2
p=np.random.randint(10,41,size=(5,5))
print(f"The Array:\n{p}")
a=p[0,:]
b=p[4,:]
c=p[1,0]
d=p[2,0]
e=p[3,0]
f=p[1,4]
g=p[2,4]
h=p[3,4]
i=(a,b,c,d,e,f,g,h)
print(i)

The Array:
[[13 14 33 29 35]
 [23 27 27 23 36]
 [16 31 10 11 22]
 [22 21 40 13 20]
 [38 26 38 37 17]]
(array([13, 14, 33, 29, 35], dtype=int32), array([38, 26, 38, 37, 17], dtype=int32), np.int32(23), np.int32(16), np.int32(22), np.int32(36), np.int32(22), np.int32(20))


In [62]:
#assignment3
#q-1
a=np.random.randint(1,12,size=(3,4))
b=np.random.randint(1,12,size=(3,4))
print(a)
print(b)
add=a+b
sub=a-b
multi=a*b
div=a/b
print(f"ADDITION:\n{add}")
print(f"SUBTRACTION:\n{sub}")
print(f"MULTIPLICATIOB:\n{multi}")
print(f"DIVISION:\n{div}")

[[ 2  4 11 11]
 [ 6  9  7  7]
 [ 2  7  2 10]]
[[10  6  1 11]
 [ 6  2  5  5]
 [ 5  5 10 11]]
ADDITION:
[[12 10 12 22]
 [12 11 12 12]
 [ 7 12 12 21]]
SUBTRACTION:
[[-8 -2 10  0]
 [ 0  7  2  2]
 [-3  2 -8 -1]]
MULTIPLICATIOB:
[[ 20  24  11 121]
 [ 36  18  35  35]
 [ 10  35  20 110]]
DIVISION:
[[ 0.2         0.66666667 11.          1.        ]
 [ 1.          4.5         1.4         1.4       ]
 [ 0.4         1.4         0.2         0.90909091]]


In [66]:
#q-2
u=np.random.randint(1,17,size=(4,4))
print(f"Og:\n{u}")
clm=np.sum(u,axis=0)
row=np.sum(u, axis=1)
print(f"Row sum:\n{row}")
print(f"Column sum:\n{clm}")

Og:
[[ 6  2 16 12]
 [ 8  6  2  5]
 [ 1 16  9  9]
 [ 6 14 15 16]]
Row sum:
[36 21 35 51]
Column sum:
[21 38 42 42]


In [68]:
#assignment4
#q-1
my=np.random.randint(1,21,size=(5,5))
print(f"The array;\n{my}")
me=np.mean(my)
print(f"Mean:{me}")
md=np.median(my)
print(f"Median{md}")
sd=np.std(my)
print(f"Stn dev:{sd}")
vr=np.var(my)
print(f"Variance:{vr}")

The array;
[[ 2  2  3 17  5]
 [15  7 10 16 16]
 [ 7 15  1 16  3]
 [11  6  7  8 18]
 [13  2 16 20  3]]
Mean:9.56
Median8.0
Stn dev:6.013850679888884
Variance:36.166399999999996


In [80]:
#q-2
n= np.arange(1, 10).reshape((3, 3))
print(f"Original:\n{n}")
Mean=np.mean(n)
standard=np.std(n)
nrml=(n-Mean)/standard
print(f"Normalized:\n{nrml}")
# print(np.mean(nrml))    #op=0.0
# print(np.std(nrml))     #op=1.0

Original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [ ]:
#assignment5
#q-1


In [ ]:
#q-2


In [ ]:
#assignment6
#q-1
